### ISSUE TITLE
Cannot center cards in a div

### ISSUE THREAD

**Issue by x8BitRain** [chandru89new/cards.sass#1]
I'm using your cards because they're really good on mobile but I cannot for the life of me figure out how to center the cards on the page, they're always stuck on the left and I'm fairly sure it's something in the Cards.css that's preventing me from doing it and I can't figure it out. 

This is as far as I've got with it on Codepen https://codepen.io/BitRain/pen/vpXjLd

I'm trying to achieve the same regular centering like this: https://codepen.io/sdthornton/pen/wBZdXq

but none of the regular CSS expressions I know of will let me center your cards when cards.css is used.

Any Ideas? Thanks.

**Comment by chandru89new** [comment]
Hey. Thanks for using this.

Re: your question, I was able to center them by doing two things:
a. removed position:absolute and added text-align: center for the #center div.
b. removed float:left for all #test
https://codepen.io/anon/pen/wpzXNJ

As such, the cards have no positioning or float. So you can fit them anywhere you want, anyway you want. You will have to make sure that the container/wrapper div that encloses the cards has the right properties to center-align its own contents. (also, make sure the width of the cards container is responsive so you dont run into width overflow issues).

**Comment by x8BitRain** [comment]
Perfect, thank you. I thought the float:left was required for the boxes to line up alongside one another, but I guess I still have more CSS to learn!

Thanks for the help and for making these nice cards.

**Comment by chandru89new** [comment]
Thank you :)
